Full_Members/Full_Members/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import home_page
from registeration.views import user_logout
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', home_page, name = 'index'),
    path('form/', include('members.urls')),
    path('registeration/', include('registeration.urls')),
    path('admin/', admin.site.urls),
    path('logout/', user_logout, name= 'logout'),
    path('places/', include('establishment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Full_Members/establishment/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from establishment.views import (addEstablishment, editEstablishment, listEstablishment,
                                 viewEstablishment, delEstablishment, index)
from django.urls import reverse

app_name = 'establishment'
urlpatterns = [
        path('', index, name= 'Index'),
        path('list/', listEstablishment.as_view(), name = 'List'),
        path('list/<int:pk>/', viewEstablishment.as_view(), name = 'Single'),
        path('add/', login_required(addEstablishment.as_view() ), name = 'Add'),
        path('edit/<int:pk>/', login_required(editEstablishment.as_view() ), name = 'Edit'),
        path('del/<int:pk>/', login_required(delEstablishment.as_view() ), name = 'Del'),

]

Full_Members/members/urls.py
from django.urls import path
from members.views import member_form, listData, dataDetails, index
from django.contrib.auth.decorators import login_required
app_name = 'members'

urlpatterns = [

        path('', index, name='Index' ),
        path('add/', member_form, name = 'mainForm'),
        path('list/', login_required(listData.as_view()), name= 'listData'),
        path('list/<int:pk>/', login_required(dataDetails.as_view()), name= 'dataDetails'),
]

Full_Members/registeration/urls.py
from django.urls import path
from registeration.views import register, index, user_login

app_name = 'registeration'
urlpatterns=[
path('', index, name = 'index'),
path('new_reg/', register, name = 'register'),
path('login/', user_login, name= 'user_login'),
]

Full_Members/templates/home.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "/css/mycss4.css" %}">
    <title></title>
  </head>
  <body>
    <nav class= "navbar navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand">Home Page</a>
      {# <a href="{% url 'index' %}">Home</a>#}
      <a href="{% url 'establishment:Index' %}">Places</a>
      <a href="{% url 'members:Index' %}">Staff</a>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'registeration:user_login' %}">Login</a>
      {% endif %}

      <a href="{% url 'admin:index'%}">Admin Page</a>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <br>
    </nav>
    <br>
  </body>
</html>