Full_Members/Full_Members/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import home_page
from registeration.views import user_logout
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', home_page, name = 'index'),
    path('form/', include('members.urls')),
    path('registeration/', include('registeration.urls')),
    path('admin/', admin.site.urls),
    path('logout/', user_logout, name= 'logout'),
    path('places/', include('establishment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Full_Members/members/urls.py
from django.urls import path
from members.views import member_form, listData, dataDetails, index
from django.contrib.auth.decorators import login_required
app_name = 'members'

urlpatterns = [

        path('', index, name='Index' ),
        path('add/', member_form, name = 'mainForm'),
        path('list/', login_required(listData.as_view()), name= 'listData'),
        path('list/<int:pk>/', login_required(dataDetails.as_view()), name= 'dataDetails'),
]

Full_Members/registeration/urls.py
from django.urls import path
from registeration.views import register, index, user_login

app_name = 'registeration'
urlpatterns=[
path('', index, name = 'index'),
path('new_reg/', register, name = 'register'),
path('login/', user_login, name= 'user_login'),
]

Full_Members/members/models.py
from django.db import models
from django.contrib.auth.models import User
from establishment.models import establishment


# Create your models here.

class member(models.Model):
    MALE = 'Mr'
    FEMALE = 'Mrs'
    GAY = "Seco"
    GENDER_CHOICES = ( (MALE, 'Male'), (FEMALE, 'Female'), (GAY, 'Gay'))

    SINGLE = 'S'
    FAMILY = 'F'
    MEMBERSHIP_CHOICES = ( (SINGLE, 'Single'), (FAMILY, 'Family') )

    User_Name = models.CharField(max_length = 12)
    First_Name = models.CharField(max_length = 16)
    Last_Name = models.CharField(max_length = 16)
    place= models.ForeignKey(establishment, on_delete=None, default= 1)
    Gender = models.CharField(max_length = 4, choices = GENDER_CHOICES,default = MALE)
    birthDay= models.DateField(default = '07/07/1977')
    Email = models.EmailField(max_length= 128)
    Memebership_type= models.CharField(max_length = 1, choices = MEMBERSHIP_CHOICES, default= SINGLE)
    profile_image = models.ImageField(upload_to = 'profiles', null = True)
    uploaded_at = models.DateTimeField(auto_now_add=True, null = True )

    def __str__ (self):
        return self.User_Name

Full_Members/members/forms.py
from django import forms
from members.models import member

class member_form(forms.ModelForm):
    class Meta:
        model = member
        fields = "__all__"
        

Full_Members/members/views.py
from django.shortcuts import render
from members import forms
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, FormView, CreateView, UpdateView, DeleteView
from members.models import member

# Create your views here.

def home_page(request):
    return render(request, 'home.html')

def index(request):
    return render(request, 'members/index.html')

@login_required
def member_form(request):
    myForm = forms.member_form()
    if request.method == 'POST':
        myForm = forms.member_form(request.POST, request.FILES)
        if myForm.is_valid():
            myForm.save()
            print ("The member's full name is: {} {}".format(myForm.cleaned_data['First_Name'] , myForm.cleaned_data['Last_Name'] ))
            return home_page(request)
    return render(request, 'members/form.html', context={'members': myForm})

class listData(ListView):
    context_object_name = 'all_members'
    model = member
    login_required = True

class dataDetails(DetailView):
    context_object_name = 'single_member'
    model = member
    template_name = 'members/details.html'
    login_required = True

Full_Members/templates/members/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "/css/mycss4.css" %}">
    <title></title>
  </head>
  <body>
    <nav class= "navbar navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand">Member Registeration</a>
      <a href="{% url 'index' %}">Home</a>
      <a href="{% url 'members:mainForm' %}">Add Data</a>
      <a href="{% url 'members:listData' %}">List Data</a>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'registeration:user_login' %}">Login</a>
      {% endif %}

      <a href="{% url 'admin:index'%}">Admin Page</a>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <br>
    </nav>
    <br>
    {% block body_block %}
    <div class="">

    </div>
    {% endblock %}
  </body>
</html>

Full_Members/templates/members/details.html
<!DOCTYPE html>
{% extends "members/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Details</title>
  </head>
  <body>

      {% block body_block %}
      <div class="container mybg1">
        <h1>Welcome to the details page</h1>
        <p>User name: {{ single_member.User_Name }}</p>
        <p>First name: {{ single_member.First_Name }}</p>
        <p>Last name: {{ single_member.Last_Name }}</p>
        <p>Work Place: {{ single_member.place }} </p>
        <p>Gender: {{ single_member.Gender }}</p>
        <p>Birthday: {{ single_member.birthDay }}</p>
        <p>Email: {{ single_member.Email }}</p>
        <p>Subscribtion: {{ single_member.Memebership_type }}</p>
        {% if  single_member.profile_image.url != ""%}
          <img src="{{ single_member.profile_image.url }}" hight= "300" width="400" alt=" where is the image?">
        {% else %}
          <p> No image uploaded for this member</p>
        {% endif %}
      </div>
      {% endblock %}


  </body>
</html>
{% endblock %}

Full_Members/templates/members/form.html
<!DOCTYPE html>
{% extends "members/base.html" %}
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block body_block %}

    <form class="form-control mybg1" action="" method="post" enctype="multipart/form-data">
      {{ members.User_Name.errors }}
      <label class="mybg3" for="{{ members.User_name.id_for_label }}">User Name:</label>
      {{ members.User_Name }}
      {% csrf_token %}

      {{ members.First_Name.errors }}
      <label class="mybg3" for="{{ members.First_name.id_for_label }}">First Name:</label>
      {{ members.First_Name }}
      {% csrf_token %}

      <p></p>

      {{ members.Last_Name.errors }}
      <label class="mybg3" for="{{ members.Last_name.id_for_label }}">Last Name:</label>
      {{ members.Last_Name }}
      {% csrf_token %}

      {{ members.place.errors }}
      <label class="mybg3" for="{{ members.Last_name.id_for_label }}">Work Place:</label>
      {{ members.place }}
      {% csrf_token %}


      {{ members.Gender.errors }}
      <label class="mybg4" for="{{ members.Gender.id_for_label }}">Gender:</label>
      {{ members.Gender }}
      {% csrf_token %}

      <p></p>

      {{ members.birthDay.errors }}
      <label class="mybg4" for="{{ members.birthDay.id_for_label }}">Birth Day:</label>
      {{ members.birthDay }}
      {% csrf_token %}

      {{ members.Memebership_type.errors }}
      <label class="mybg4" for="{{ members.Memebership_type.id_for_label }}">Memebership type:</label>
      {{ members.Memebership_type }}
      {% csrf_token %}

      <p></p>

      {{ members.Email.errors }}
      <label class="mybg3" for="{{ members.Email.id_for_label }}">Email:</label>
      {{ members.Email }}
      {% csrf_token %}

      <p></p>

      {{ members.profile_image.errors }}
      <label class="mybg2" for="{{ members.profile_image.id_for_label }}">profile image:</label>
      {{ members.profile_image }}

      <!-- {% csrf_token %} -->


      <p></p>

      <input type="submit" class="btn btn-outline-danger btn-lg" name="" value="Submit">

    </form>
    {% endblock %}
  </body>
</html>

Full_Members/templates/members/index.html
<!DOCTYPE html>
{% extends "members/base.html" %}
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    {% block body_block %}
    <div class="mybg1">
      <h1>Welcome To The home Pgae</h1>
    </div>

    {% endblock %}

  </body>
</html>

Full_Members/templates/members/member_list.html
<!DOCTYPE html>
{% extends "members/base.html" %}
{% load staticfiles %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>List Data</title>
  </head>
  <body>
    {% block body_block %}
    <ol>
      {% for m in all_members %}
        <h3><li> <a href="{{ m.id }}">{{ m.User_Name }}</a> </li></h3>
      {% endfor %}
    </ol>
    {% endblock %}


  </body>
</html>