Full_Members/Full_Members/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import home_page
from registeration.views import user_logout
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', home_page, name = 'index'),
    path('form/', include('members.urls')),
    path('registeration/', include('registeration.urls')),
    path('admin/', admin.site.urls),
    path('logout/', user_logout, name= 'logout'),
    path('places/', include('establishment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Full_Members/establishment/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from establishment.views import (addEstablishment, editEstablishment, listEstablishment,
                                 viewEstablishment, delEstablishment, index)
from django.urls import reverse

app_name = 'establishment'
urlpatterns = [
        path('', index, name= 'Index'),
        path('list/', listEstablishment.as_view(), name = 'List'),
        path('list/<int:pk>/', viewEstablishment.as_view(), name = 'Single'),
        path('add/', login_required(addEstablishment.as_view() ), name = 'Add'),
        path('edit/<int:pk>/', login_required(editEstablishment.as_view() ), name = 'Edit'),
        path('del/<int:pk>/', login_required(delEstablishment.as_view() ), name = 'Del'),

]

Full_Members/members/urls.py
from django.urls import path
from members.views import member_form, listData, dataDetails, index
from django.contrib.auth.decorators import login_required
app_name = 'members'

urlpatterns = [

        path('', index, name='Index' ),
        path('add/', member_form, name = 'mainForm'),
        path('list/', login_required(listData.as_view()), name= 'listData'),
        path('list/<int:pk>/', login_required(dataDetails.as_view()), name= 'dataDetails'),
]

Full_Members/registeration/urls.py
from django.urls import path
from registeration.views import register, index, user_login

app_name = 'registeration'
urlpatterns=[
path('', index, name = 'index'),
path('new_reg/', register, name = 'register'),
path('login/', user_login, name= 'user_login'),
]

Full_Members/establishment/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class establishment(models.Model):

    HOTEL = 'Hotel'
    SPA = 'SPA'
    RESORT = 'Resort'
    GOLF = 'Golf Clube'
    COUNTRY = 'Country Club'
    MULTI = 'Multi Service'
    E_Types = ( (HOTEL, 'Hotel'), (SPA, 'SPA'), (RESORT, 'Resort'),(GOLF, 'Golf Clube'),
               (COUNTRY, 'Country Club'), (MULTI, 'Multi Service') )

    ONE = '1'
    TWO = '2'
    THREE = '3'
    FOUR = '4'
    FIVE ='5'
    SIX = '6'
    SEVEN = '7'

    StarsCount = ( (ONE, '1'), (TWO, '2'), (THREE, '3'), (FOUR, '4'), (FIVE,'5'), (SIX, '6'), (SEVEN, '7') )

    Name = models.CharField(max_length = 32, unique= True)
    Establishment_type = models.CharField (max_length= 13, choices = E_Types)
    Stars = models.CharField (max_length = 1, choices = StarsCount)
    Adress = models.CharField(max_length = 128)
    Phone = models.CharField(max_length = 13)
    Web_Adress = models.URLField (max_length = 32, null= True)
    Email = models.EmailField (max_length = 36)
    Main_Photo = models.ImageField (upload_to = 'company_images', null =True)
    About = models.TextField (max_length=256, null = True )
    Logo = models.ImageField (upload_to = 'logos', null = True)

    def get_absolute_url(self):
        return reverse('establishment:Single',kwargs={'pk':self.pk})


    def __str__ (self):
        return self.Name

Full_Members/establishment/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from establishment.models import establishment
from django.urls import reverse_lazy

# Create your views here.

def index(request):
    return render(request, 'establishment/index.html')


class addEstablishment(CreateView):
    model = establishment
    fields = '__all__'


class editEstablishment(UpdateView):
    model = establishment
    fields = '__all__'


class viewEstablishment(DetailView):
    model = establishment
    context_object_name = 'single_establishment'
    template_name = 'establishment/details.html'


class listEstablishment(ListView):
    model = establishment
    context_object_name = 'all_establishments'




class delEstablishment(DeleteView):
    model = establishment
    success_url = reverse_lazy('establishment:List')

Full_Members/templates/establishment/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "/css/mycss4.css" %}">
    <title></title>
  </head>
  <body>
    <nav class= "navbar navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand">Establishment Registeration</a>
      <a href="{% url 'establishment:Index' %}">Places Main Page</a>
      <a href="{% url 'establishment:Add' %}">Add New Place</a>
      <a href="{% url 'establishment:List' %}">List Places</a>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'registeration:user_login' %}">Login</a>
      {% endif %}
      <a href="{% url 'index' %}">Home</a>
      <a href="{% url 'admin:index'%}">Admin Page</a>

      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <br>
    </nav>
    <br>
    {% block body_block %}
    <div class="">

    </div>
    {% endblock %}
  </body>
</html>

Full_Members/templates/establishment/details.html
{% extends "establishment/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block body_block %}
      <div class="container mybg1">
        <p></p>
        <h2 class="mybg2">{{ single_establishment.Name }}</h2>

        <p></p>
        {% if single_establishment.Logo.url != '' %}
          <img src="{{ single_establishment.Logo.url }}" hight= "100" width= "100" alt="">
        {% else %}
          <p>-------</p>
        {% endif %}
        <p></p>
        <p>Grade: {{ single_establishment.Stars }} star</p>
        <p>Establishment type: {{ single_establishment.Establishment_type }}</p>
        <p>Adress: {{ single_establishment.Adress }}</p>
        <p>Phone: {{ single_establishment.Phone }}</p>
        <p> Web Site: <a href="{{ single_establishment.Web_Adress }}">{{ single_establishment.Web_Adress }}</a> </p>
        <p> Email {{ single_establishment.Email }}</p>
        {% if single_establishment.Main_Photo.url != '' %}
          <img src="{{ single_establishment.Main_Photo.url }}" hight= "400" width="600" alt="">
        {% endif %}
        <p></p>
        <h3>About: </h3>
        <div class="container">

          <textarea name="name" rows="6" cols="60" readonly>{{ single_establishment.About }}</textarea>

          <p></p>
        </div class="mybg4">
        <p></p>
        <a class="btn btn-warning " href="{% url 'establishment:Edit' pk=single_establishment.pk %}">Edit Place</a>
        <a class="btn btn-danger" href="{% url 'establishment:Del' pk=single_establishment.pk %}">Delete!</a>

      </div>
      <div class="container">


      </div>
    {% endblock %}

    </body>
</html>

{% endblock %}

Full_Members/templates/establishment/establishment_confirm_delete.html
{% extends "establishment/base.html" %}


<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block body_block %}
      <h1 class="mybg1">Are you sure you want to DELETE {{ establishment.Name }} ?</h1>
      <form class="container form-control mybg3" action="{% url 'establishment:Del' pk=establishment.pk %}" method="post">
        {% csrf_token %}
        <input type="Submit" class="btn btn-danger" value="Delete">
        <a class="btn btn-primary" href="{% url 'establishment:Single' pk=establishment.pk %}">Cancel</a>
      </form>

    {% endblock %}
  </body>
</html>

Full_Members/templates/establishment/establishment_form.html
{% extends "establishment/base.html" %}


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> </title>
  </head>
  <body>
    {% block body_block %}
      <h1>
        {% if not form.isnatce.pk %}
          Add Establishment
        {% else %}
          Edit Establishment
        {% endif %}
      </h1>

      <form class="container form-control mybg1" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary"  name="" value="submit">

      </form>
    {% endblock %}
  </body>
</html>

Full_Members/templates/establishment/establishment_list.html
<!DOCTYPE html>
{% extends "establishment/base.html" %}
{% load  staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block body_block %}

        <ol>
          {% for e in all_establishments  %}
            <li><a href="{{ e.id }}"> {{ e.Name }}</a></li>
          {% endfor %}
        </ol>




    {% endblock %}
  </body>
</html>

Full_Members/templates/establishment/index.html
{% extends "establishment/base.html" %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    {% block body_block %}
    <div class="mybg1">
      <h1>Welcome To The Places Page</h1>
    </div>

    {% endblock %}

  </body>
</html>